use_frameworks!

platform :ios, '8.0'

target 'LZLogining_Example' do
  pod 'LZLogining', :path => '../'

  target 'LZLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
